name: scan_score
description: "Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  google_mlkit_barcode_scanning: ^0.14.1
  camera: ^0.11.3
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  path: ^1.9.1
  csv: ^6.0.0
  permission_handler: ^12.0.1
  image: ^4.5.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  share_plus: ^10.0.3
  archive: ^4.0.7

  # 用于获取安卓版本号
  device_info_plus: ^10.1.0
  # 用于 Android 11+ 调用系统原生保存 (Scoped Storage)
  flutter_file_dialog: ^3.0.2
  liquid_glass_renderer: ^0.2.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sample_data/
